import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
export default function Onboarding() {
    const [step, setStep] = useState(1);
    const [platformEmail, setPlatformEmail] = useState("");
    const [redditConnected, setRedditConnected] = useState(false);
    const [quoraConnected, setQuoraConnected] = useState(false);
    const steps = [
        { number: 1, label: "Connect" },
        { number: 2, label: "Accounts" },
        { number: 3, label: "Configure" },
        { number: 4, label: "Activate" },
    ];
    const handleNextStep = () => {
        if (step < 4)
            setStep(step + 1);
    };
    const handlePrevStep = () => {
        if (step > 1)
            setStep(step - 1);
    };
    return (_jsx("div", { className: "min-h-screen bg-[#f8f9fa] flex items-center justify-center p-4", children: _jsxs("div", { className: "w-full max-w-[520px] bg-white rounded-2xl border border-gray-200 shadow-lg overflow-hidden", children: [_jsxs("div", { className: "border-b border-gray-200 px-6 py-4", children: [_jsx("h1", { className: "text-lg font-semibold text-gray-900", children: "Setup Forum Agent" }), _jsxs("p", { className: "text-sm text-gray-600 mt-1", children: ["Step ", step, " of 4"] })] }), _jsx("div", { className: "px-6 py-4 border-b border-gray-200", children: _jsx("div", { className: "flex gap-2", children: steps.map((s) => (_jsx("div", { className: `flex-1 h-2 rounded-full transition ${s.number <= step ? "bg-orange-600" : "bg-gray-200"}` }, s.number))) }) }), _jsxs("div", { className: "p-6 min-h-[300px]", children: [step === 1 && (_jsxs("div", { className: "space-y-4", children: [_jsx("h2", { className: "text-lg font-semibold text-gray-900", children: "Connect Your Account" }), _jsx("p", { className: "text-sm text-gray-600", children: "Enter your ClickSendAI email to get started" }), _jsx("input", { type: "email", placeholder: "you@example.com", value: platformEmail, onChange: (e) => setPlatformEmail(e.target.value), className: "w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-orange-500 focus:border-transparent" })] })), step === 2 && (_jsxs("div", { className: "space-y-4", children: [_jsx("h2", { className: "text-lg font-semibold text-gray-900", children: "Connect Accounts" }), _jsx("p", { className: "text-sm text-gray-600", children: "Connect your Reddit and Quora accounts" }), _jsxs("div", { className: "space-y-3", children: [_jsx("button", { onClick: () => setRedditConnected(!redditConnected), className: `w-full px-4 py-3 rounded-lg border-2 font-medium transition ${redditConnected
                                                ? "border-orange-600 bg-orange-50 text-orange-600"
                                                : "border-gray-300 bg-white text-gray-600 hover:border-orange-600"}`, children: redditConnected ? "✓ Reddit Connected" : "Connect Reddit" }), _jsx("button", { onClick: () => setQuoraConnected(!quoraConnected), className: `w-full px-4 py-3 rounded-lg border-2 font-medium transition ${quoraConnected
                                                ? "border-orange-600 bg-orange-50 text-orange-600"
                                                : "border-gray-300 bg-white text-gray-600 hover:border-orange-600"}`, children: quoraConnected ? "✓ Quora Connected" : "Connect Quora" })] })] })), step === 3 && (_jsxs("div", { className: "space-y-4", children: [_jsx("h2", { className: "text-lg font-semibold text-gray-900", children: "Configure Agent" }), _jsx("p", { className: "text-sm text-gray-600", children: "Set up your agent's keywords and preferences" }), _jsxs("div", { className: "space-y-3", children: [_jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-900 mb-2", children: "Niche" }), _jsx("input", { type: "text", placeholder: "e.g., Fitness Coaching", className: "w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-orange-500 focus:border-transparent" })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-900 mb-2", children: "Keywords (comma separated)" }), _jsx("input", { type: "text", placeholder: "keyword1, keyword2, keyword3", className: "w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-orange-500 focus:border-transparent" })] })] })] })), step === 4 && (_jsxs("div", { className: "space-y-4", children: [_jsx("h2", { className: "text-lg font-semibold text-gray-900", children: "All Set!" }), _jsx("p", { className: "text-sm text-gray-600", children: "Your forum agent is ready to start scanning and posting" }), _jsxs("div", { className: "bg-emerald-50 border border-emerald-200 rounded-lg p-4 text-center", children: [_jsx("p", { className: "text-sm font-medium text-emerald-700", children: "Setup Complete" }), _jsx("p", { className: "text-xs text-emerald-600 mt-1", children: "The agent will start scanning forums automatically" })] })] }))] }), _jsxs("div", { className: "border-t border-gray-200 px-6 py-4 flex gap-3", children: [_jsx("button", { onClick: handlePrevStep, disabled: step === 1, className: "flex-1 px-4 py-2 border border-gray-300 hover:border-gray-400 disabled:opacity-50 disabled:cursor-not-allowed text-gray-900 rounded-lg font-medium transition", children: "Back" }), _jsx("button", { onClick: handleNextStep, disabled: step === 4, className: "flex-1 px-4 py-2 bg-orange-600 hover:bg-orange-700 disabled:opacity-50 disabled:cursor-not-allowed text-white rounded-lg font-medium transition", children: step === 4 ? "Done" : "Next" })] })] }) }));
}
