/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const useEffect: typeof import('react')['useEffect']
  const useNavigate: typeof import('react-router-dom')['useNavigate']
  const useState: typeof import('react')['useState']
}
